from resources.skill_type_resource import SkillTypeResource, SkillTypeById
from resources.skill_resource import SkillResource, SkillById
from resources.tech_project_resource import TechProjectResource, TechProjectById
from resources.project_skill_resource import ProjectSkillResource, ProjectSkillById