"""Add relationships

Revision ID: a2ff456041e6
Revises: d5f6a3136a56
Create Date: 2024-09-30 20:23:37.991278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ff456041e6'
down_revision = 'd5f6a3136a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('tech_project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tech_projects', ['tech_project_id'], ['id'])
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'])

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'skill_types', ['skill_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_type_id')

    with op.batch_alter_table('project_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_id')
        batch_op.drop_column('tech_project_id')
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
