"""Create tables

Revision ID: d5f6a3136a56
Revises: 
Create Date: 2024-09-30 19:44:38.152670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f6a3136a56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tech_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('key_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('work_no', sa.Integer(), nullable=False),
    sa.Column('first_version_date', sa.Date(), nullable=False),
    sa.Column('current_version_date', sa.Date(), nullable=False),
    sa.Column('github_link', sa.String(), nullable=True),
    sa.Column('demo_link', sa.String(), nullable=True),
    sa.Column('live_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('work_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_projects')
    op.drop_table('skills')
    op.drop_table('skill_types')
    op.drop_table('project_skills')
    # ### end Alembic commands ###
